# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.daemon=false

# Fabric Properties
minecraft_version=26.1.1
loader_version=0.18.6
loom_version=1.15-SNAPSHOT

# Fabric API
fabric_version=0.145.3+26.1.1

# Mod Properties
mod_version=1.2.3
maven_group=me.cortex.voxy.addon.hypixel
archives_base_name=voxy-hypixel-addon

# Dependencies
hm_api_version=1.0.3+26.1